-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 17:45:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema apilman
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apilman
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apilman` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `apilman` ;

-- -----------------------------------------------------
-- Table `apilman`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apilman`.`user` (
  `id` VARCHAR(64) NOT NULL,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `verification_code` INT NOT NULL,
  `is_verificated` TINYINT NOT NULL DEFAULT '0',
  `tier` VARCHAR(45) NOT NULL DEFAULT 'bronze',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `apilman`.`path`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apilman`.`path` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NOT NULL,
  `url` VARCHAR(256) NOT NULL,
  `api_key` VARCHAR(256) NULL DEFAULT NULL,
  `key` VARCHAR(64) NOT NULL,
  `company` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `usage` INT NOT NULL DEFAULT '0',
  `price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_path_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_path_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `apilman`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `apilman`.`api_usage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apilman`.`api_usage` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(64) NOT NULL,
  `path_id` VARCHAR(64) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `fk_usage_path_idx` (`path_id` ASC) VISIBLE,
  INDEX `fk_usage_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_usage_path`
    FOREIGN KEY (`path_id`)
    REFERENCES `apilman`.`path` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usage_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `apilman`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 125
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `apilman`.`error_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apilman`.`error_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(64) NOT NULL,
  `path_id` VARCHAR(64) NOT NULL,
  `error_msg` VARCHAR(255) NULL DEFAULT NULL,
  `company` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_logs_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_logs_path_idx` (`path_id` ASC) VISIBLE,
  CONSTRAINT `fk_logs_path`
    FOREIGN KEY (`path_id`)
    REFERENCES `apilman`.`path` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_logs_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `apilman`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
